name: CI/CD for My C# Application

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'  # Adjust to your .NET version

    - name: Build and Publish
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o ./publish

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2
      with:
        server: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        ssh_private_key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        local_path: ./publish/
        remote_path: /var/www/myapp  # Adjust to your deployment path
