name: Deploy to Server

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'  # Adjust to your .NET Core 8 version

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish -c Release -o ./publish

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v0.2.0
      with:
        server: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
        local: ./publish  # Path to the published files on GitHub runner
        remote: /var/www/myapp  # Remote path where files should be copied

    - name: Clean up
      run: rm -rf ./publish
