name: Deploy to Server

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --no-build --output ./output

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
        script: |
          # Make sure the target directory exists
          mkdir -p /var/www/EmployeeApp
          # Copy the published files
          scp -r ./output/* user@${{ secrets.SERVER_HOST }}:/var/www/EmployeeApp
          # Optionally, restart your application or web server
          sudo systemctl restart EmployeeApp.service
