name: CI/CD for My C# Application

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Use .NET 8.0 SDK

    - name: Build and Publish
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o ./publish

    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Deploy to Server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
        SERVER_SSH_PASSWORD: ${{ secrets.SERVER_SSH_PASSWORD }}
        SSH_PORT: ${{ secrets.SERVER_SSH_PORT }}  # Adjust if your SSH port is different
      run: |
        sshpass -p "$SERVER_SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SERVER_USERNAME@$SERVER_IP "mkdir -p /var/www/myapp"

        # Copy published files to server
        sshpass -p "$SERVER_SSH_PASSWORD" scp -o StrictHostKeyChecking=no -P $SSH_PORT -r ./publish/* $SERVER_USERNAME@$SERVER_IP:/var/www/myapp

        # Restart application (replace with your application specific command)
        sshpass -p "$SERVER_SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SERVER_USERNAME@$SERVER_IP "sudo systemctl restart myapp"
