name: CI/CD for My C# Application

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Use .NET 8.0 SDK

    - name: Build and Publish
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o ./publish

    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        SSH_PASSPHRASE: ${{ secrets.SERVER_SSH_PASSPHRASE }}
      run: |
        # Save the SSH private key to a file
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key

        # Use sshpass to handle the SSH passphrase
        sshpass -p "$SSH_PASSPHRASE" ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} 'mkdir -p /var/www/myapp'
        sshpass -p "$SSH_PASSPHRASE" scp -o StrictHostKeyChecking=no -i private_key -r ./publish/* ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}:/var/www/myapp
        sshpass -p "$SSH_PASSPHRASE" ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} 'sudo systemctl restart myapp'
      shell: bash
