name: Deploy to Server

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: self-hosted
    name: Test-Deploy

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --no-build --output ./output

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
        script: |
          # Create the target directory with sudo and -S option for password input
          echo ${{ secrets.SERVER_PASSWORD }} | sudo -S mkdir -p /var/www/demo.archost.online
          # Copy the published files with sudo
          echo sudo -S cp -r ~/actions-runner/_work/EmployeeManagement/EmployeeManagement/output/* /var/www/demo.archost.online
          # Restart the application or web server 
          sudo -S systemctl restart EmployeeApp.service
